spring:
  datasource:
    generate-unique-name: false
    url: 'jdbc:h2:mem:test'
    username: sa
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    path: /
